// Generated by Dabacog at 2020-11-02 00:47:38 UTC.
package com.nilsign.dabacog.demo;

import java.lang.String;

class Address {
  private long id;

  private String street;

  private String zipcode;

  private String city;

  public long getId() {
    return id;
  }

  public void setId(long id) {
    this.id = id;
  }

  public String getStreet() {
    return street;
  }

  public void setStreet(String street) {
    this.Street = Street;
  }

  public String getZipcode() {
    return zipcode;
  }

  public void setZipcode(String zipcode) {
    this.Zipcode = Zipcode;
  }

  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.City = City;
  }
}
