// Generated by Dabacog at 2020-11-02 00:47:38 UTC.
package com.nilsign.dabacog.demo;

import java.lang.String;

class Book {
  private long id;

  private Author author;

  private Genre genre;

  private Location location;

  private String name;

  private String isbn;

  private double price;

  public long getId() {
    return id;
  }

  public void setId(long id) {
    this.id = id;
  }

  public Author getAuthor() {
    return author;
  }

  public void setAuthor(Author author) {
    this.Author = Author;
  }

  public Genre getGenre() {
    return genre;
  }

  public void setGenre(Genre genre) {
    this.Genre = Genre;
  }

  public Location getLocation() {
    return location;
  }

  public void setLocation(Location location) {
    this.Location = Location;
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.Name = Name;
  }

  public String getIsbn() {
    return isbn;
  }

  public void setIsbn(String isbn) {
    this.Isbn = Isbn;
  }

  public double getPrice() {
    return price;
  }

  public void setPrice(double price) {
    this.Price = Price;
  }
}
