// Generated by Dabacog at 2020-11-02 00:47:38 UTC.
package com.nilsign.dabacog.demo;

import java.lang.String;

class Contact {
  private long id;

  private Customer customer;

  private String mobile;

  private String home;

  private String email;

  public long getId() {
    return id;
  }

  public void setId(long id) {
    this.id = id;
  }

  public Customer getCustomer() {
    return customer;
  }

  public void setCustomer(Customer customer) {
    this.Customer = Customer;
  }

  public String getMobile() {
    return mobile;
  }

  public void setMobile(String mobile) {
    this.Mobile = Mobile;
  }

  public String getHome() {
    return home;
  }

  public void setHome(String home) {
    this.Home = Home;
  }

  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.Email = Email;
  }
}
