// Generated by Dabacog at 2020-11-02 00:47:38 UTC.
package com.nilsign.dabacog.demo;

import java.lang.String;

class Customer {
  private long id;

  private Address address;

  private Contact contact;

  private String firstName;

  private String lastName;

  public long getId() {
    return id;
  }

  public void setId(long id) {
    this.id = id;
  }

  public Address getAddress() {
    return address;
  }

  public void setAddress(Address address) {
    this.Address = Address;
  }

  public Contact getContact() {
    return contact;
  }

  public void setContact(Contact contact) {
    this.Contact = Contact;
  }

  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.FirstName = FirstName;
  }

  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.LastName = LastName;
  }
}
