// Generated by Dabacog at 2020-11-02 00:47:38 UTC.
package com.nilsign.dabacog.demo;

import java.lang.String;

class Employee {
  private long id;

  private Employee employee;

  private Address address;

  private String firstName;

  private String lastName;

  public long getId() {
    return id;
  }

  public void setId(long id) {
    this.id = id;
  }

  public Employee getEmployee() {
    return employee;
  }

  public void setEmployee(Employee employee) {
    this.Employee = Employee;
  }

  public Address getAddress() {
    return address;
  }

  public void setAddress(Address address) {
    this.Address = Address;
  }

  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.FirstName = FirstName;
  }

  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.LastName = LastName;
  }
}
