// Generated by Dabacog at 2020-11-02 00:47:38 UTC.
package com.nilsign.dabacog.demo;

import java.util.Date;

class Loan {
  private long id;

  private Book book;

  private Customer customer;

  private Date starts;

  private Date ends;

  private Date returns;

  private boolean dunningLetter;

  public long getId() {
    return id;
  }

  public void setId(long id) {
    this.id = id;
  }

  public Book getBook() {
    return book;
  }

  public void setBook(Book book) {
    this.Book = Book;
  }

  public Customer getCustomer() {
    return customer;
  }

  public void setCustomer(Customer customer) {
    this.Customer = Customer;
  }

  public Date getStarts() {
    return starts;
  }

  public void setStarts(Date starts) {
    this.Starts = Starts;
  }

  public Date getEnds() {
    return ends;
  }

  public void setEnds(Date ends) {
    this.Ends = Ends;
  }

  public Date getReturns() {
    return returns;
  }

  public void setReturns(Date returns) {
    this.Returns = Returns;
  }

  public boolean getDunningLetter() {
    return dunningLetter;
  }

  public void setDunningLetter(boolean dunningLetter) {
    this.DunningLetter = DunningLetter;
  }
}
