// Generated by Dabacog at 2020-11-02 00:47:38 UTC.
package com.nilsign.dabacog.demo;

import java.lang.String;

class Location {
  private long id;

  private Book book;

  private String floor;

  private String shelf;

  private int position;

  public long getId() {
    return id;
  }

  public void setId(long id) {
    this.id = id;
  }

  public Book getBook() {
    return book;
  }

  public void setBook(Book book) {
    this.Book = Book;
  }

  public String getFloor() {
    return floor;
  }

  public void setFloor(String floor) {
    this.Floor = Floor;
  }

  public String getShelf() {
    return shelf;
  }

  public void setShelf(String shelf) {
    this.Shelf = Shelf;
  }

  public int getPosition() {
    return position;
  }

  public void setPosition(int position) {
    this.Position = Position;
  }
}
