package com.nilsign.generators;

import com.nilsign.dxd.model.DxdModel;
import com.nilsign.helper.FileHelper;
import lombok.AccessLevel;
import lombok.NonNull;
import lombok.RequiredArgsConstructor;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.TimeZone;

@RequiredArgsConstructor(access = AccessLevel.PROTECTED)
public abstract class Generator {

  @NonNull
  protected final DxdModel model;

  protected abstract String getOutputDirectory();
  protected abstract String getOutputFileName();

  public static String buildGeneratedByComment() {
    SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
    formatter.setTimeZone(TimeZone.getTimeZone("UTC"));
    return String.format(
        "Generated by Dabacog at %s UTC.\n",
        formatter.format(new Date()));
  }

  public String getOutputFilePath() {
    String filePath = FileHelper.createDirectoriesIfNotExist(getOutputDirectory());
    if (filePath.startsWith(".\\") || (filePath.startsWith("./"))){
      filePath = filePath.substring(2);
    }
    return FileHelper.normalizePath(filePath) + getOutputFileName().trim();
  }

  public File createOutputFile() {
    String filePath = getOutputFilePath();
    FileHelper.deleteFileIfExists(filePath);
    try {
      return FileHelper.createFileIfNotExists(filePath);
    } catch (Exception e) {
      throw new RuntimeException(
          String.format("Failed to create target file '%s'.", filePath),
          e);
    }
  }
}
